name: Deploy Terraform to Azure

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Export Azure credentials for Terraform
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" > azure-credentials.json
        echo "ARM_CLIENT_ID=$(jq -r .clientId azure-credentials.json)" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azure-credentials.json)" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure-credentials.json)" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=$(jq -r .tenantId azure-credentials.json)" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init
      working-directory: .

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: .

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: .
